# Generated by Django 6.0.1 on 2026-05-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_email',
        ),
    ]
